name: Chasing Daylight
analytics: {}
purpose: []
github: true
description: 'Cycling in North Negros, Philippines'
author:
  name: Raoul Benedicto
  email: raoulbenedicto@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.7577885430545943
color:
  lightness: 0.24823022057486716
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  saturation: 0.5594492380428913
  brandStrength: 0.9543679206945592
  rhythmicContrast: 0.22641616380146456
content_rating:
  adult: false
typography_spectrum: 0.16970667235018447
opengraph: {}
title: Chasing Daylight
url: 'https://chasingdaylight.bike'
